### ISSUE TITLE
3.9 Support

### ISSUE THREAD

**Issue by CodeFanaticX** [extremecoders-re/uncompyle6-builds#1]
I thought it will work up to 3.10
But 3.9 failed

# Unsupported Python version, 3.9.0, for decompilation

**Comment by extremecoders-re** [comment]
Uncompyle6 supports Python 2.4 to 3.8. 
3.9 and 3.10 are unsupported. Updated the README.

https://github.com/rocky/python-uncompyle6/#introduction
